SCMO-9896 Enabled extraction of array elements in transform-request/response plugins
cloudentity/pyron pull request #90
Opened 2021-06-23 15:29 UTC by chrisAlex128

Example of a JSON object with nested array:
```json
{
  "people": [
    {
      "name": "Joe",
      "age": 38
    },
    {
      "name": "Don",
      "age": 44
    }
  ]
}
```

For reference `$body.people.[0].name`, the result is `"Joe"`
For reference `$body.people.[1]`, the result is `{"name":"Don","age":44}`

If index is out-of-bounds or references a missing attribute, the return value is `None` (bubbling up as JSON `null`).

More detailed examples in `ValueResolverTest.scala`.

2021-06-26 20:09 UTC, mnikliborc requested changes
Looks good. Please add paragraph `Set body attribute to array element` next to https://github.com/cloudentity/pyron/blob/dev/docs/plugins/transform-request.md#set-body-attribute-to-request-attribute explaining new feature usage (docs from PR's overview is good, maybe use example to be in line with other examples in the docs)

2021-06-28 14:43 UTC, chrisAlex128 commented
> Looks good. Please add paragraph `Set body attribute to array element` next to https://github.com/cloudentity/pyron/blob/dev/docs/plugins/transform-request.md#set-body-attribute-to-request-attribute explaining new feature usage (docs from PR's overview is good, maybe use example to be in line with other examples in the docs)

Thanks @mnikliborc . I've made the docs updates, so please take a look.

2021-06-28 22:03 UTC, mnikliborc approved these changes

2021-06-28 22:07 UTC, ce-rbabu approved these changes

2021-06-28 22:20 UTC, merged